version: '3'


vars: 
  VERSION:
    sh: git describe --tags --always
  PINGER_IMAGE: chronark/planetfall-pinger
  SCHEDULER_IMAGE: chronark/planetfall-scheduler

tasks:
  clear:
    cmds:
      - rm -rf ./**/node_modules
      - rm -rf ./**/dist
      - rm -rf ./**/.next
      - rm -rf ./**/.turbo
  install:
    deps: 
      - clear
    cmds:
      - pnpm install
  build:
    deps:
      - install
    cmds:
      - pnpm build
  
  deploy:
    deps:
      - clear
    env:
          TF_VAR_pinger_image: "{{.PINGER_IMAGE}}:{{.VERSION}}"
          TF_VAR_scheduler_image: "{{.SCHEDULER_IMAGE}}:{{.VERSION}}"
    cmds:
      - task: build-scheduler
      - task: build-pinger
       
      - fly machines update --app=planetfall-scheduler 6e82975b764e68 --image={{.SCHEDULER_IMAGE}}:{{.VERSION}} --yes
      - terraform -chdir=deployment init -upgrade
      - terraform -chdir=deployment apply -var-file=".tfvars" -auto-approve
       
     
  build-pinger:
    - task: build-docker
      vars:
        DOCKERFILE: apps/proxy/Dockerfile
        IMAGE: chronark/planetfall-pinger

  build-scheduler:
    - task: build-docker
      vars:
        DOCKERFILE: apps/scheduler/Dockerfile
        IMAGE: chronark/planetfall-scheduler
    
  build-docker:
    internal: true
    run: when_changed
    env:
      DOCKER_BUILDKIT: 1
    cmds:
      - docker build --platform=linux/amd64 -t {{.IMAGE}}:{{.VERSION}} -t {{.IMAGE}}:latest -f {{.DOCKERFILE}} .
      - docker push {{.IMAGE}}:{{.VERSION}}
      - docker push {{.IMAGE}}:latest
    