// Generated by Xata Codegen 0.18.0. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  { name: "checks", columns: [] },
  {
    name: "API",
    columns: [
      { name: "method", type: "string", notNull: true, defaultValue: "POST" },
      { name: "name", type: "string" },
      { name: "url", type: "string", notNull: true, defaultValue: '""' },
    ],
  },
  { name: "status_page", columns: [] },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Andreas-Thomas-s-workspace-kmog9h.eu-west-1.xata.sh/db/planetfall",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
