import { Platform, Region, PrismaClient } from "@prisma/client";

const awsRegions: Region[] = [
  {
    id: `${Platform.aws}:af-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://fwvbnvbb6oz2jzgpovm75hb4540twgye.lambda-url.af-south-1.on.aws",
    region: "af-south-1",
    name: "Cape Town, South Africa",
  },
  {
    id: `${Platform.aws}:ap-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://pzfcpsl6rah7ob2qcirdbdwoxi0mprfy.lambda-url.ap-east-1.on.aws",
    region: "ap-east-1",
    name: "Hong Kong",
  },
  {
    id: `${Platform.aws}:ap-northeast-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://aedkpukrqw2v2xoxiyxqtw2jye0sxqgj.lambda-url.ap-northeast-1.on.aws",
    region: "ap-northeast-1",
    name: "Tokyo, Japan",
  },
  {
    id: `${Platform.aws}:ap-northeast-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://srbdfu4sloqa36m365l2hxj3zy0sfxgd.lambda-url.ap-northeast-2.on.aws",
    region: "ap-northeast-2",
    name: "Seoul, South Korea",
  },
  {
    id: `${Platform.aws}:ap-northeast-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://otqwy4ztlzxbfsqblo6aippqne0zsosn.lambda-url.ap-northeast-3.on.aws",
    region: "ap-northeast-3",
    name: "Osaka, Japan",
  },
  {
    id: `${Platform.aws}:ap-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://z3sxifqdguqafynsgno7oszvlu0vmlvj.lambda-url.ap-south-1.on.aws",
    region: "ap-south-1",
    name: "Mumbai, India",
  },
  {
    id: `${Platform.aws}:ap-southeast-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://x7gipm6xm43azjux7pocbauzde0sktuf.lambda-url.ap-southeast-1.on.aws",
    region: "ap-southeast-1",
    name: "Singapore",
  },
  {
    id: `${Platform.aws}:ap-southeast-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://quiz2c6reccroj4nfanpg5ugam0bwkjn.lambda-url.ap-southeast-2.on.aws",
    region: "ap-southeast-2",
    name: "Sydney, Australia",
  },
  {
    id: `${Platform.aws}:ap-southeast-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://yarzmqqceswzdjiumxjhxb6wp40hfmon.lambda-url.ap-southeast-3.on.aws",
    region: "ap-southeast-3",
    name: "Jakarta, Indonesia",
  },
  {
    id: `${Platform.aws}:ca-central-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://lbmzunimpea2xn6avrxatagc340bhqcz.lambda-url.ca-central-1.on.aws",
    region: "ca-central-1",
    name: "Montreal, Canada",
  },
  {
    id: `${Platform.aws}:eu-central-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://anurwjl4ys7a4sd5taw2l7yswm0weooh.lambda-url.eu-central-1.on.aws",
    region: "eu-central-1",
    name: "Frankfurt, Germany",
  },
  {
    id: `${Platform.aws}:eu-north-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://nm5a2nt7arvrdmkpmghsuw6gbm0jmoud.lambda-url.eu-north-1.on.aws",
    region: "eu-north-1",
    name: "Stockholm, Sweden",
  },
  {
    id: `${Platform.aws}:eu-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://emmt56urfbjlcsz7g5pthurwra0dpyyb.lambda-url.eu-south-1.on.aws",
    region: "eu-south-1",
    name: "Milan, Italy",
  },
  {
    id: `${Platform.aws}:eu-west-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://euyfmjginq73yhz2u2ctkoz2te0vovcl.lambda-url.eu-west-1.on.aws",
    region: "eu-west-1",
    name: "Dublin, Ireland",
  },
  {
    id: `${Platform.aws}:eu-west-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://x223heggtqzliqdnjf7ptr64qq0yggsb.lambda-url.eu-west-2.on.aws",
    region: "eu-west-2",
    name: "London, UK",
  },
  {
    id: `${Platform.aws}:eu-west-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://p7jcbz4gj6gy74brseg66gyx3y0mfxqo.lambda-url.eu-west-3.on.aws",
    region: "eu-west-3",
    name: "Paris, France",
  },
  {
    id: `${Platform.aws}:me-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://ebv5syscefvfqaq27ryuh2bydm0aeuwn.lambda-url.me-south-1.on.aws",
    region: "me-south-1",
    name: "Bahrain",
  },
  {
    id: `${Platform.aws}:sa-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://nqx75bedph5vsytqrywnxotufm0xckzy.lambda-url.sa-east-1.on.aws",
    region: "sa-east-1",
    name: "São Paulo, Brazil",
  },
  {
    id: `${Platform.aws}:us-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://6dt2klkvdaryvh3pjb4osro4ky0lqtqo.lambda-url.us-east-1.on.aws",
    region: "us-east-1",
    name: "N. Virginia, US",
  },
  {
    id: `${Platform.aws}:us-east-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://ydlfvu24gdqqgowde72tt5zjee0zifnt.lambda-url.us-east-2.on.aws",
    region: "us-east-2",
    name: "Ohio, US, ",
  },
  {
    id: `${Platform.aws}:us-west-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://dj7qjsq2vjlzyg75zkqogfmwxu0cwcyp.lambda-url.us-west-1.on.aws",
    region: "us-west-1",
    name: "N. California, US",
  },
  {
    id: `${Platform.aws}:us-west-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://sqkhjigvvpijz65inuixu6vhum0ppsqp.lambda-url.us-west-2.on.aws",
    region: "us-west-2",
    name: "Oregon, US",
  },
];
const edgeRegions: Region[] = [
  {
    id: `${Platform.vercelEdge}:arn1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/arn1",
    region: "arn1",
    name: "Stockholm, Sweden",
  },
  {
    id: `${Platform.vercelEdge}:bom1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/bom1",
    region: "bom1",
    name: "Mumbai, India",
  },
  {
    id: `${Platform.vercelEdge}:cdg1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/cdg1",
    region: "cdg1",
    name: "Paris, France",
  },
  {
    id: `${Platform.vercelEdge}:cle1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/cle1",
    region: "cle1",
    name: "Cleveland, US",
  },
  {
    id: `${Platform.vercelEdge}:cpt1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/cpt1",
    region: "cpt1",
    name: "Cape Town, South Africa",
  },
  {
    id: `${Platform.vercelEdge}:dub1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/dub1",
    region: "dub1",
    name: "Dublin, Ireland",
  },
  {
    id: `${Platform.vercelEdge}:fra1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/fra1",
    region: "fra1",
    name: "Frankfurt, Germany",
  },
  {
    id: `${Platform.vercelEdge}:gru1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/gru1",
    region: "gru1",
    name: "São Paulo, Brazil",
  },
  {
    id: `${Platform.vercelEdge}:hkg1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/hkg1",
    region: "hkg1",
    name: "Hong Kong",
  },
  {
    id: `${Platform.vercelEdge}:hnd1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/hnd1",
    region: "hnd1",
    name: "Tokyo, Japan",
  },
  {
    id: `${Platform.vercelEdge}:iad1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/iad1",
    region: "iad1",
    name: "Washington, D.C., US",
  },
  {
    id: `${Platform.vercelEdge}:icn1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/icn1",
    region: "icn1",
    name: "Seoul, South Korea",
  },
  {
    id: `${Platform.vercelEdge}:kix1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/kix1",
    region: "kix1",
    name: "Osaka, Japan",
  },
  {
    id: `${Platform.vercelEdge}:lhr1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/lhr1",
    region: "lhr1",
    name: "London, United Kingdom",
  },
  {
    id: `${Platform.vercelEdge}:pdx1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/pdx1",
    region: "pdx1",
    name: "Portland, US",
  },
  {
    id: `${Platform.vercelEdge}:sfo1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/sfo1",
    region: "sfo1",
    name: "San Francisco, US",
  },
  {
    id: `${Platform.vercelEdge}:sin1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/sin1",
    region: "sin1",
    name: "Singapore",
  },
  {
    id: `${Platform.vercelEdge}:syd1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall.io/api/v1/edge-ping/syd1",
    region: "syd1",
    name: "Sydney, Australia",
  },
];
const customVercelEdgeConfigRegions: Region[] = [
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:arn1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/arn1",
    region: "arn1",
    name: "Stockholm, Sweden",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:bom1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/bom1",
    region: "bom1",
    name: "Mumbai, India",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cdg1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cdg1",
    region: "cdg1",
    name: "Paris, France",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cle1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cle1",
    region: "cle1",
    name: "Cleveland, US",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cpt1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cpt1",
    region: "cpt1",
    name: "Cape Town, South Africa",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:dub1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/dub1",
    region: "dub1",
    name: "Dublin, Ireland",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:fra1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/fra1",
    region: "fra1",
    name: "Frankfurt, Germany",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:gru1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/gru1",
    region: "gru1",
    name: "São Paulo, Brazil",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:hkg1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/hkg1",
    region: "hkg1",
    name: "Hong Kong",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:hnd1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/hnd1",
    region: "hnd1",
    name: "Tokyo, Japan",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:iad1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/iad1",
    region: "iad1",
    name: "Washington, D.C., US",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:icn1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/icn1",
    region: "icn1",
    name: "Seoul, South Korea",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:kix1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/kix1",
    region: "kix1",
    name: "Osaka, Japan",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:lhr1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/lhr1",
    region: "lhr1",
    name: "London, United Kingdom",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:pdx1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/pdx1",
    region: "pdx1",
    name: "Portland, US",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:sfo1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/sfo1",
    region: "sfo1",
    name: "San Francisco, US",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:sin1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/sin1",
    region: "sin1",
    name: "Singapore",
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:syd1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/syd1",
    region: "syd1",
    name: "Sydney, Australia",
  },
];
const flyRegions: Region[] = [
  {
    id: `${Platform.fly}:ams`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ams",
    region: "ams",
    name: "Amsterdam, Netherlands",
  },
  {
    id: `${Platform.fly}:cdg`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/cdg",
    region: "cdg",
    name: "Paris, France",
  },
  {
    id: `${Platform.fly}:den`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/den",
    region: "den",
    name: "Denver, Colorado (US)",
  },
  {
    id: `${Platform.fly}:dfw`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/dfw",
    region: "dfw",
    name: "Dallas, Texas (US)",
  },
  {
    id: `${Platform.fly}:ewr`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ewr",
    region: "ewr",
    name: "Secaucus, NJ (US)",
  },
  {
    id: `${Platform.fly}:fra`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/fra",
    region: "fra",
    name: "Frankfurt, Germany",
  },
  {
    id: `${Platform.fly}:gru`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/gru",
    region: "gru",
    name: "São Paulo",
  },
  {
    id: `${Platform.fly}:hkg`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/hkg",
    region: "hkg",
    name: "Hong Kong, Hong Kong",
  },
  {
    id: `${Platform.fly}:iad`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/iad",
    region: "iad",
    name: "Ashburn, Virginia (US)",
  },
  {
    id: `${Platform.fly}:jnb`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/jnb",
    region: "jnb",
    name: "Johannesburg, South Africa",
  },
  {
    id: `${Platform.fly}:lax`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/lax",
    region: "lax",
    name: "Los Angeles, California (US)",
  },
  {
    id: `${Platform.fly}:lhr`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/lhr",
    region: "lhr",
    name: "London, United Kingdom",
  },
  {
    id: `${Platform.fly}:maa`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/maa",
    region: "maa",
    name: "Chennai (Madras), India",
  },
  {
    id: `${Platform.fly}:mad`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/mad",
    region: "mad",
    name: "Madrid, Spain",
  },
  {
    id: `${Platform.fly}:mia`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/mia",
    region: "mia",
    name: "Miami, Florida (US)",
  },
  {
    id: `${Platform.fly}:nrt`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/nrt",
    region: "nrt",
    name: "Tokyo, Japan",
  },
  {
    id: `${Platform.fly}:ord`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ord",
    region: "ord",
    name: "Chicago, Illinois (US)",
  },
  {
    id: `${Platform.fly}:otp`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/otp",
    region: "otp",
    name: "Bucharest, Romania",
  },
  {
    id: `${Platform.fly}:scl`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/scl",
    region: "scl",
    name: "Santiago, Chile",
  },
  {
    id: `${Platform.fly}:sea`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sea",
    region: "sea",
    name: "Seattle, Washington (US)",
  },
  {
    id: `${Platform.fly}:sin`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sin",
    region: "sin",
    name: "Singapore",
  },
  {
    id: `${Platform.fly}:sjc`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sjc",
    region: "sjc",
    name: "Sunnyvale, California (US)",
  },
  {
    id: `${Platform.fly}:syd`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/syd",
    region: "syd",
    name: "Sydney, Australia",
  },
  {
    id: `${Platform.fly}:waw`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/waw",
    region: "waw",
    name: "Warsaw, Poland",
  },
  {
    id: `${Platform.fly}:yul`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/yul",
    region: "yul",
    name: "Montreal, Canada	",
  },
  {
    id: `${Platform.fly}:yyz`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/yyz",
    region: "yyz",
    name: "Toronto, Canada",
  },
];

const regions: Region[] = [
  ...edgeRegions,
  ...awsRegions,
  ...flyRegions,
  ...customVercelEdgeConfigRegions,
];

async function main() {
  const db = new PrismaClient();
  for (const region of regions) {
    console.log("Upserting", region.id, region.url);
    await db.region.upsert({
      where: {
        id: region.id,
      },
      update: region,
      create: region,
    });
  }

  await db.$disconnect();
}

main();
