import { Platform, PrismaClient, Region } from "@prisma/client";

const awsRegions: Region[] = [
  {
    id: `${Platform.aws}:af-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://fwvbnvbb6oz2jzgpovm75hb4540twgye.lambda-url.af-south-1.on.aws",
    region: "af-south-1",
    name: "Cape Town, South Africa",
    lat: -33.9249,
    lon: 18.4241,
  },
  {
    id: `${Platform.aws}:ap-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://pzfcpsl6rah7ob2qcirdbdwoxi0mprfy.lambda-url.ap-east-1.on.aws",
    region: "ap-east-1",
    name: "Hong Kong",
    lat: 22.3193,
    lon: 114.1694,
  },
  {
    id: `${Platform.aws}:ap-northeast-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://aedkpukrqw2v2xoxiyxqtw2jye0sxqgj.lambda-url.ap-northeast-1.on.aws",
    region: "ap-northeast-1",
    name: "Tokyo, Japan",
    lat: 35.6895,
    lon: 139.6917,
  },

  {
    id: `${Platform.aws}:ap-northeast-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://srbdfu4sloqa36m365l2hxj3zy0sfxgd.lambda-url.ap-northeast-2.on.aws",
    region: "ap-northeast-2",
    name: "Seoul, South Korea",
    lat: 37.5665,
    lon: 126.978,
  },
  {
    id: `${Platform.aws}:ap-northeast-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://otqwy4ztlzxbfsqblo6aippqne0zsosn.lambda-url.ap-northeast-3.on.aws",
    region: "ap-northeast-3",
    name: "Osaka, Japan",
    lat: 35.6895,
    lon: 139.6917,
  },
  {
    id: `${Platform.aws}:ap-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://z3sxifqdguqafynsgno7oszvlu0vmlvj.lambda-url.ap-south-1.on.aws",
    region: "ap-south-1",
    name: "Mumbai, India",
    lat: 19.076,
    lon: 72.8777,
  },
  {
    id: `${Platform.aws}:ap-southeast-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://x7gipm6xm43azjux7pocbauzde0sktuf.lambda-url.ap-southeast-1.on.aws",
    region: "ap-southeast-1",
    name: "Singapore",
    lat: 1.3521,
    lon: 103.8198,
  },
  {
    id: `${Platform.aws}:ap-southeast-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://quiz2c6reccroj4nfanpg5ugam0bwkjn.lambda-url.ap-southeast-2.on.aws",
    region: "ap-southeast-2",
    name: "Sydney, Australia",

    lat: -33.8688,
    lon: 151.2093,
  },
  {
    id: `${Platform.aws}:ap-southeast-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://yarzmqqceswzdjiumxjhxb6wp40hfmon.lambda-url.ap-southeast-3.on.aws",
    region: "ap-southeast-3",
    name: "Jakarta, Indonesia",
    lat: -6.175,
    lon: 106.8275,
  },
  {
    id: `${Platform.aws}:ca-central-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://lbmzunimpea2xn6avrxatagc340bhqcz.lambda-url.ca-central-1.on.aws",
    region: "ca-central-1",
    name: "Montreal, Canada",
    lat: 45.5017,
    lon: -73.5673,
  },
  {
    id: `${Platform.aws}:eu-central-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://anurwjl4ys7a4sd5taw2l7yswm0weooh.lambda-url.eu-central-1.on.aws",
    region: "eu-central-1",
    name: "Frankfurt, Germany",
    lat: 50.1109,
    lon: 8.6821,
  },
  {
    id: `${Platform.aws}:eu-north-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://nm5a2nt7arvrdmkpmghsuw6gbm0jmoud.lambda-url.eu-north-1.on.aws",
    region: "eu-north-1",
    name: "Stockholm, Sweden",
    lat: 59.3293,
    lon: 18.0686,
  },
  {
    id: `${Platform.aws}:eu-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://emmt56urfbjlcsz7g5pthurwra0dpyyb.lambda-url.eu-south-1.on.aws",
    region: "eu-south-1",
    name: "Milan, Italy",
    lat: 45.464664,
    lon: 9.18854,
  },
  {
    id: `${Platform.aws}:eu-west-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://euyfmjginq73yhz2u2ctkoz2te0vovcl.lambda-url.eu-west-1.on.aws",
    region: "eu-west-1",
    name: "Dublin, Ireland",
    lat: 53.3498,
    lon: -6.2603,
  },
  {
    id: `${Platform.aws}:eu-west-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://x223heggtqzliqdnjf7ptr64qq0yggsb.lambda-url.eu-west-2.on.aws",
    region: "eu-west-2",
    name: "London, UK",
    lat: 51.5074,
    lon: -0.1278,
  },
  {
    id: `${Platform.aws}:eu-west-3`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://p7jcbz4gj6gy74brseg66gyx3y0mfxqo.lambda-url.eu-west-3.on.aws",
    region: "eu-west-3",
    name: "Paris, France",
    lat: 48.8566,
    lon: 2.3522,
  },
  {
    id: `${Platform.aws}:me-south-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://ebv5syscefvfqaq27ryuh2bydm0aeuwn.lambda-url.me-south-1.on.aws",
    region: "me-south-1",
    name: "Bahrain",
    lat: 26.0667,
    lon: 50.5577,
  },
  {
    id: `${Platform.aws}:sa-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://nqx75bedph5vsytqrywnxotufm0xckzy.lambda-url.sa-east-1.on.aws",
    region: "sa-east-1",
    name: "São Paulo, Brazil",
    lat: -23.5505,
    lon: -46.6333,
  },
  {
    id: `${Platform.aws}:us-east-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://6dt2klkvdaryvh3pjb4osro4ky0lqtqo.lambda-url.us-east-1.on.aws",
    region: "us-east-1",
    name: "N. Virginia, US",
    lat: 37.4316,
    lon: -78.6569,
  },
  {
    id: `${Platform.aws}:us-east-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://ydlfvu24gdqqgowde72tt5zjee0zifnt.lambda-url.us-east-2.on.aws",
    region: "us-east-2",
    name: "Ohio, US",
    lat: 40.3736,
    lon: -82.7755,
  },
  {
    id: `${Platform.aws}:us-west-1`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://dj7qjsq2vjlzyg75zkqogfmwxu0cwcyp.lambda-url.us-west-1.on.aws",
    region: "us-west-1",
    name: "N. California, US",
    lat: 40.4173,
    lon: -82.9071,
  },
  {
    id: `${Platform.aws}:us-west-2`,
    platform: Platform.aws,
    custom: null,
    visible: true,
    url: "https://sqkhjigvvpijz65inuixu6vhum0ppsqp.lambda-url.us-west-2.on.aws",
    region: "us-west-2",
    name: "Oregon, US",
    lat: 43.8041,
    lon: -120.5542,
  },
];
const edgeRegions: Region[] = [
  {
    id: `${Platform.vercelEdge}:arn1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/arn1",
    region: "arn1",
    name: "Stockholm, Sweden",
    lat: 59.3293,
    lon: 18.0686,
  },
  {
    id: `${Platform.vercelEdge}:bom1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/bom1",
    region: "bom1",
    name: "Mumbai, India",
    lat: 19.076,
    lon: 72.8777,
  },
  {
    id: `${Platform.vercelEdge}:cdg1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/cdg1",
    region: "cdg1",
    name: "Paris, France",
    lat: 48.8566,
    lon: 2.3522,
  },
  {
    id: `${Platform.vercelEdge}:cle1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/cle1",
    region: "cle1",
    name: "Cleveland, US",
    lat: 41.505493,
    lon: -81.68129,
  },
  {
    id: `${Platform.vercelEdge}:cpt1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/cpt1",
    region: "cpt1",
    name: "Cape Town, South Africa",
    lat: -33.918861,
    lon: 18.4233,
  },
  {
    id: `${Platform.vercelEdge}:dub1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/dub1",
    region: "dub1",
    name: "Dublin, Ireland",
    lat: 53.35014,
    lon: -6.266155,
  },
  {
    id: `${Platform.vercelEdge}:fra1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/fra1",
    region: "fra1",
    name: "Frankfurt, Germany",
    lat: 50.11552,
    lon: 8.68417,
  },
  {
    id: `${Platform.vercelEdge}:gru1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/gru1",
    region: "gru1",
    name: "São Paulo, Brazil",
    lat: -23.533773,
    lon: -46.62529,
  },
  {
    id: `${Platform.vercelEdge}:hkg1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/hkg1",
    region: "hkg1",
    name: "Hong Kong",
    lat: 22.302711,
    lon: 114.177216,
  },
  {
    id: `${Platform.vercelEdge}:hnd1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/hnd1",
    region: "hnd1",
    name: "Tokyo, Japan",
    lat: 35.652832,
    lon: 139.839478,
  },
  {
    id: `${Platform.vercelEdge}:iad1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/iad1",
    region: "iad1",
    name: "Washington, D.C., US",
    lat: 38.889805,
    lon: -77.009056,
  },
  {
    id: `${Platform.vercelEdge}:icn1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/icn1",
    region: "icn1",
    name: "Seoul, South Korea",
    lat: 37.517235,
    lon: 127.047325,
  },
  {
    id: `${Platform.vercelEdge}:kix1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/kix1",
    region: "kix1",
    name: "Osaka, Japan",
    lat: 34.672314,
    lon: 135.484802,
  },
  {
    id: `${Platform.vercelEdge}:lhr1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/lhr1",
    region: "lhr1",
    name: "London, United Kingdom",
    lat: 51.509865,
    lon: -0.118092,
  },
  {
    id: `${Platform.vercelEdge}:pdx1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/pdx1",
    region: "pdx1",
    name: "Portland, US",
    lat: 45.523064,
    lon: -122.676483,
  },
  {
    id: `${Platform.vercelEdge}:sfo1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/sfo1",
    region: "sfo1",
    name: "San Francisco, US",
    lat: 37.773972,
    lon: -122.431297,
  },
  {
    id: `${Platform.vercelEdge}:sin1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/sin1",
    region: "sin1",
    name: "Singapore",
    lat: 1.3521,
    lon: 103.8198,
  },
  {
    id: `${Platform.vercelEdge}:syd1`,
    platform: Platform.vercelEdge,
    custom: null,
    visible: true,
    url: "https://planetfall-edge-runner.vercel.app/api/v1/syd1",
    region: "syd1",
    name: "Sydney, Australia",
    lat: 33.8688,
    lon: 151.2093,
  },
];
const customVercelEdgeConfigRegions: Region[] = [
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:arn1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/arn1",
    region: "arn1",
    name: "Stockholm, Sweden",
    lat: 59.3293,
    lon: 18.0686,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:bom1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/bom1",
    region: "bom1",
    name: "Mumbai, India",
    lat: 19.076,
    lon: 72.8777,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cdg1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cdg1",
    region: "cdg1",
    name: "Paris, France",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cle1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cle1",
    region: "cle1",
    name: "Cleveland, US",
    lat: 48.8566,
    lon: 2.3522,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:cpt1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/cpt1",
    region: "cpt1",
    name: "Cape Town, South Africa",
    lat: -33.9249,
    lon: 18.4241,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:dub1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/dub1",
    region: "dub1",
    name: "Dublin, Ireland",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:fra1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/fra1",
    region: "fra1",
    name: "Frankfurt, Germany",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:gru1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/gru1",
    region: "gru1",
    name: "São Paulo, Brazil",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:hkg1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/hkg1",
    region: "hkg1",
    name: "Hong Kong",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:hnd1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/hnd1",
    region: "hnd1",
    name: "Tokyo, Japan",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:iad1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/iad1",
    region: "iad1",
    name: "Washington, D.C., US",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:icn1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/icn1",
    region: "icn1",
    name: "Seoul, South Korea",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:kix1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/kix1",
    region: "kix1",
    name: "Osaka, Japan",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:lhr1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/lhr1",
    region: "lhr1",
    name: "London, United Kingdom",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:pdx1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/pdx1",
    region: "pdx1",
    name: "Portland, US",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:sfo1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/sfo1",
    region: "sfo1",
    name: "San Francisco, US",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:sin1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/sin1",
    region: "sin1",
    name: "Singapore",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.vercelEdge}:custom:vercel-edge-config:syd1`,
    platform: Platform.vercelEdge,
    visible: false,
    custom: "vercel-edge-config",
    url: "https://planetfall-vercel-edge-config.vercel.app/api/syd1",
    region: "syd1",
    name: "Sydney, Australia",
    lat: null,
    lon: null,
  },
];
const flyRegions: Region[] = [
  {
    id: `${Platform.fly}:ams`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ams",
    region: "ams",
    name: "Amsterdam, Netherlands",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:cdg`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/cdg",
    region: "cdg",
    name: "Paris, France",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:den`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/den",
    region: "den",
    name: "Denver, Colorado (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:dfw`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/dfw",
    region: "dfw",
    name: "Dallas, Texas (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:ewr`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ewr",
    region: "ewr",
    name: "Secaucus, NJ (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:fra`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/fra",
    region: "fra",
    name: "Frankfurt, Germany",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:gru`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/gru",
    region: "gru",
    name: "São Paulo",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:hkg`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/hkg",
    region: "hkg",
    name: "Hong Kong, Hong Kong",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:iad`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/iad",
    region: "iad",
    name: "Ashburn, Virginia (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:jnb`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/jnb",
    region: "jnb",
    name: "Johannesburg, South Africa",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:lax`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/lax",
    region: "lax",
    name: "Los Angeles, California (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:lhr`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/lhr",
    region: "lhr",
    name: "London, United Kingdom",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:bom`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/bom",
    region: "bom",
    name: "Bombay, India",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:mad`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/mad",
    region: "mad",
    name: "Madrid, Spain",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:mia`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/mia",
    region: "mia",
    name: "Miami, Florida (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:nrt`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/nrt",
    region: "nrt",
    name: "Tokyo, Japan",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:ord`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/ord",
    region: "ord",
    name: "Chicago, Illinois (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:otp`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/otp",
    region: "otp",
    name: "Bucharest, Romania",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:scl`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/scl",
    region: "scl",
    name: "Santiago, Chile",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:sea`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sea",
    region: "sea",
    name: "Seattle, Washington (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:sin`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sin",
    region: "sin",
    name: "Singapore",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:sjc`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/sjc",
    region: "sjc",
    name: "Sunnyvale, California (US)",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:syd`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/syd",
    region: "syd",
    name: "Sydney, Australia",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:waw`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/waw",
    region: "waw",
    name: "Warsaw, Poland",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:yul`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/yul",
    region: "yul",
    name: "Montreal, Canada	",
    lat: null,
    lon: null,
  },
  {
    id: `${Platform.fly}:yyz`,
    platform: Platform.fly,
    custom: null,
    visible: true,
    url: "https://planetfall-check-runner.fly.dev/ping/yyz",
    region: "yyz",
    name: "Toronto, Canada",
    lat: null,
    lon: null,
  },
];

const regions: Region[] = [
  ...edgeRegions,
  ...awsRegions,
  ...flyRegions,
  ...customVercelEdgeConfigRegions,
];

async function main() {
  const db = new PrismaClient();
  for (const region of regions) {
    console.log("Upserting", region.id, region.url);
    await db.region.upsert({
      where: {
        id: region.id,
      },
      update: region,
      create: region,
    });
  }

  await db.$disconnect();
}

main();
