name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Scheduler
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chronark/planetfall-scheduler:${{env.VERSION}}
          context: .
          file: apps/scheduler/Dockerfile
      - name: Build Check Runner
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chronark/planetfall-check-runner:${{env.VERSION}}
          context: .
          file: apps/proxy/Dockerfile